### ISSUE TITLE
frontend-build: High security vulnerability needs semver-regex update (via image-webpack-loader)

### ISSUE THREAD

**Issue by dianekaplan** [openedx/frontend-wg#107]
High: Regular Expression Denial of Service (ReDOS)     
Patched in semver-regex version  >=3.1.3    
dependency chain:  @edx/frontend-build > image-webpack-loader > imagemin-gifsicle > gifsicle > bin-wrapper > bin-version-check > bin-version > find-versions >  semver-regex          
more info: https://github.com/advisories/GHSA-44c6-4v22-4mhx   

It looks like frontend-build currently uses image-webpack-loader 8.1.0, which only uses semver-regex version 2.0.0. (We need to update image-webpack-loader to a version that uses semver-regex >=3.1.3).

### PRs

- [ ] https://github.com/openedx/frontend-build/pull/259

**Comment by mamankhan99** [comment]
8.1.0 is the latest version of image-webpack-loader, we can not update it at the moment. Should we wait for the patch or do you have a suggestion?

**Comment by jmbowman** [comment]
It looks like the issue has been flagged upstream but there has not yet been a response: https://github.com/tcoopman/image-webpack-loader/issues/414 .  Could you go ahead and create a PR upstream to address it?

**Comment by jmbowman** [comment]
@mamankhan99 Are you (or anybody else on FED-BOM) up for creating an upstream PR as suggested above?

**Comment by mamankhan99** [comment]
We can but we will need to create PRs from bin-version to image-webpack-loader to fix the issue. Should we proceed?

**Comment by jmbowman** [comment]
Sorry for not seeing this earlier.  I'm ok with that, but is there an alternative we can use instead of image-webpack-loader?  The [webpack docs](https://webpack.js.org/plugins/image-minimizer-webpack-plugin/) mention [image-minimizer-webpack-plugin](https://www.npmjs.com/package/image-minimizer-webpack-plugin) , is that the preferred library for this functionality now?  Is it in a better state of maintenance?  There's some relevant discussion in https://github.com/webpack-contrib/image-minimizer-webpack-plugin/issues/225 .

**Comment by mamankhan99** [comment]
Yes! we can replacte it with [image-minimizer-webpack-plugin](https://www.npmjs.com/package/image-minimizer-webpack-plugin). Let me discuss the feasibility with my team and then we can start working on it.

**Comment by BilalQamar95** [comment]
We are using v8.1.0 of `image-webpack-loader` which is the latest version. The package is bundled with following optimizers
`imagemin-gifsicle`: Imagemin plugin for [Gifsicle](https://www.lcdf.org/gifsicle/) (_Compress GIF images_)
`imagemin-mozjpeg`: Imagemin plugin for [mozjpeg](https://github.com/mozilla/mozjpeg) (_Compress JPEG images_)
`image-pngquant`: Imagemin plugin for  [pngquant](https://github.com/imagemin/imagemin-pngquant) (_Compress PNG images_)

Dependency chain for these optimizers is as follow:
imagemin-gifsicle > gifsicle > bin-wrapper > bin-version-check > bin-version > find-versions > semver-regex
imagemin-mozjpeg > mozjpeg > bin-wrapper > bin-version-check > bin-version > find-versions > semver-regex
iimagemin-pngquant> pngquant-bin > bin-wrapper > bin-version-check > bin-version > find-versions > semver-regex

All of them have dependency on `bin-wrapper`. The latest version of `bin-wrapper` is using `bin-version-check: 4.0.0 `which is using `semver-regex: 2.0`.
The issues lies with (latest version of) `bin-wrapper` using outdated `bin-version-check`. ([bin-wrapper PR](https://github.com/kevva/bin-wrapper/pull/80/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R43) updating `bin-version-check` to latest version, bumping `semver-regex` to v4.

We can replace `image-webpack-loader` with [image-minimizer-webpack-plugin](https://www.npmjs.com/package/image-minimizer-webpack-plugin), as long as we also move away from `imagemin`
[imagemin](https://github.com/imagemin/imagemin) - optimize your images by default, since it is stable and works with all types of images
[squoosh](https://github.com/GoogleChromeLabs/squoosh/tree/dev/libsquoosh) - while working in experimental mode with .jpg, .jpeg, .png, .webp, .avif file types.
[sharp](https://github.com/lovell/sharp) - High performance Node.js image processing, to resize and compress JPEG, PNG, WebP, AVIF and TIFF images. Uses the libvips library.

Since imagemin is depending on aforementioned plugins(gifsicle, mozjpeg, pngquant), we would have to consider squoosh in order to avoid ReDOS. This will work fine for PNG & JPG but there is no support for GIF.

[Npm trends](https://npmtrends.com/image-minimizer-webpack-plugin-vs-imagemin-vs-imagemin-webpack-plugin-vs-jimp-vs-responsive-loader)

**Comment by arbrandes** [comment]
@BilalQamar95, @jmbowman, are we moving forward with `image-minimizer-webpack-plugin`?  For what it's worth, `sharp` looks nice and unbloated.

**Comment by BilalQamar95** [comment]
> Replaced `image-webpack-loader` with `image-minimizer-webpack-plugin` openedx/frontend-build#259

The shift is required to resolve ReDOS, a High security vulnerability due to `semver-regex`. The [PR for it ](https://github.com/openedx/frontend-build/pull/259)is waiting on a re-review from Adam

**Comment by arbrandes** [comment]
@BilalQamar95, thanks!  I hadn't noticed the PR existed.
