### ISSUE TITLE
Node 16 Upgrade: Initial survey and determine plan of action

### ISSUE THREAD

**Issue by davidjoy** [openedx/frontend-wg#2]
Prior to the Maple release being cut on October 9, we need to upgrade node to v16.  

Note, Prospectus and the edX website team are considering being guinea pigs and starting to upgrade to node 16 themselves.  This is a good thing.

A task describing the upgrade from Node 8 to 12: https://openedx.atlassian.net/browse/ARCH-352

# How do we find versions we need to upgrade?

Tech ownership spreadsheet?

# Action Items

- [x] @davidjoy Go talk to Diana.  She ran this upgrade the last time from 8 to 12 and probably knows what we need to do.
- [x] @binodpant Enterprise Information gathering (add sections here for different areas of the codebase, dump information, get us the complete picture)
- [ ] @muselesscreator Content information gathering (find places we're using node 12)
- [ ] @davidjoy Engagement information gathering
- [ ] @davidjoy Open edX information gathering
- [ ] @adamstankiewicz Upgrade npm from 6.x to 7.x?  Is this related to the node upgrade or can they be separated?
- [ ] @davidjoy edx-platform and other legacy IDAs
- [ ] Note that node-sass less than 6.x does not support node 16.  We use node-sass 5.x in Paragon.  See some details here: https://stackoverflow.com/questions/67241196/error-no-template-named-remove-cv-t-in-namespace-std-did-you-mean-remove
 - [x] @binodpant  determine what needs to be done next to merge https://github.com/edx/frontend-app-profile/pull/491 
  - [ ] @binodpant determine/do if frontend-platform can be upgrade on its own to use new node, without impacting current workflows of devs/MFEs
  - [ ] @binodpant determine what changes are needed in frontend-build and frontend-platform to successfully build a MFE that depends on it, using npm upgrade 
  - [ ] finish investigation/changes around enterprise MFE peer deps failing with upgrade attempt
  - [ ] what steps if any the owners of the various MFE repos need to take (within edX) 
  - [ ] communication around getting ready with an install of nvm on devs' systems to be sent out
  - [ ] what steps should be published for external committers
  - [ ] where/how to document the steps devs may need to take post the upgrade 

# Things to check for each repo/project

- [x] Github actions workflows: will be automated by ArbiBOM tooling will create PRs for upgrades
- [x ] travis.yml
- [x] Tubular build scripts? ArbiBOM will handle
- [x] .nvmrc added to repos: NOT NEEDED ANYMORE! ArbiBom will handle this via modernizr
- [x] Check package.json for evidence of node versions ("engines")
- [x] Write up a clear set of instructions and options for getting the work done (You do it, we do it, BD does it, etc.)
- [x] Communication: get engineers to update their dev environments
- [x] Docker (docker-compose.yml, etc.)
- [x] AMIs? (Amazon machine images, may manifest in Terraform)
- [x] prospectus (website is upgrading it)

### Enterprise

By: @binodpant 

Terraform check: I don't see the word `npm` in edx-terraform, so ... 

#### edx-enterprise
- [x] add .nvmrc: N/A
- [x] `npm i` at https://github.com/edx/edx-enterprise/blob/3aa114c410854b4def58f8f75cb106a610d8754e/Makefile#L127 (should update doc for users to use nvmrc)
- [x] GH ci.yml should use nvmrc if possible: https://github.com/edx/edx-enterprise/blob/289ae6a6fe148c7471f531bd7ac8bca39fa7e0a1/.github/workflows/ci.yml#L35
- [x] This package.json may need `engines` setup: https://github.com/edx/edx-enterprise/blob/3aa114c410854b4def58f8f75cb106a610d8754e/package.json

#### learner portal
- [x] engines in package.json
- [x] nvmrc usage in ci.yml? (Uses hardcoded node_version 12) we can use this perhaps: https://github.com/marketplace/actions/read-nvmrc

#### admin portal
Uses hardcoded node_version 12
- [x] engines in package.json
- [x] nvmrc usage in ci.yml? ( Uses hardcoded node_version 12)

#### public catalog
https://github.com/edx/frontend-app-enterprise-public-catalog/blob/main/.github/workflows/ci.yml
Uses hardcoded node_version 12
- [x] engines in package.json
- [x] nvmrc usage in ci.yml? ( Uses hardcoded node_version 12)

#### frontend-enterprise 
- [x] GH workflows needs nvmrc: https://github.com/edx/frontend-enterprise/tree/master/.github/workflows
- [x] Engines changes

**Comment by adamstankiewicz** [comment]
Notes from meeting on 9/14:

@adamstankiewicz @binodpant @muselesscreator 

* We're going to keep NPM v7 upgrade alongside Node 16 upgrade, but figure out where peer dependencies need to be updated to have semver ranges. @adamstankiewicz to take this on as an action item. We will prioritize this work.
* @binodpant continue investigation into package.json engines to determine if they're needed, or what they actually do (e.g., throw warnings).
* Binod also added some stuff related to Enterprise above.
* Using nvm locally should be enforced to ensure consistency. Package.json engines may be helpful here. Documentation might help too in READMEs or PR templates (e.g., `frontend-build`, `frontend-platform`), but because it's for _each_ frontend related repo, it's tricky... Could this be part of `fedx-scripts` in frontend-build to enforce versions while trying to execute commands such as `start`, `test`, etc.? Do you have ``.nvmrc` file locally and `nvm` installed? Commands work if you have everything necessary (@adamstankiewicz)
* Binod asks are there any conflicts between React 17 and Node 16 upgrades? TBD. @binodpant

**Comment by adamstankiewicz** [comment]
We may also want to look into using node-alpine to reduce image size. Some more details here: https://blog.tarkalabs.com/how-to-reduce-nodejs-docker-image-by-70-e799b3d3396a

**Comment by binodpant** [comment]
I find, sort of as expected, that when trying to upgrade node in an Enterprise repo like Enterprise learner portal we get an error like this 

```
~/work/frontend-app-learner-portal-enterprise (master ✘)✖✹ ᐅ npm i  
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: frontend-app-learner-portal-enterprise@0.1.0
npm ERR! Found: @edx/paragon@16.14.7
npm ERR! node_modules/@edx/paragon
npm ERR!   @edx/paragon@"16.14.7" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @edx/paragon@">=10.0.0 <15.0.0" from @edx/frontend-platform@1.11.0
npm ERR! node_modules/@edx/frontend-platform
npm ERR!   @edx/frontend-platform@"1.11.0" from the root project
npm ERR!   peer @edx/frontend-platform@"^1.8.0" from @edx/frontend-component-footer@10.1.0
npm ERR!   node_modules/@edx/frontend-component-footer
npm ERR!     @edx/frontend-component-footer@"10.1.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/binodpant/.npm/eresolve-report.txt for a full report.

```

so yes this reveals that for projects that use frontend-platform, we will need to some legwork on the platform repo to help address this

this may serve as a starting point for working on some of the repoes, upgrade-wise

**Comment by davidjoy** [comment]
To me this means we're now forced to make sure our peer dependencies are "correct".  Annoying, but probably healthy. :)

**Comment by binodpant** [comment]
Quick status:

Could not spend much time this week on this, but here is the latest:

- I think I got everything needed for an npm/node upgrade for the frontend-app-profile repo, so that should be set to merge once approved
- Next steps:
  - determine what needs to be done next to merge https://github.com/edx/frontend-app-profile/pull/491 
  - determine what changes are needed in frontend-build and frontend-platform to successfully build a MFE that depends on it, using npm upgrade 
  - what steps if any the owners of the various MFE repos need to take (within edX) 
  - communication around getting ready with an install of nvm on devs' systems to be sent out
  - what steps should be published for external committers
  - where/how to document the steps devs may need to take post the upgrade

**Comment by davidjoy** [comment]
Some useful things I just discovered:

1. nvm suggests some code you can add to your shell's profile to get automatic node/npm version switching.  Find your shell here: https://github.com/nvm-sh/nvm#deeper-shell-integration. I tried the zsh version just now, and it worked great.
2. If you put an .nvmrc in your workspace directory above all your repos and put `12` in it, you'll switch back to node 12/npm 6 for all your frontend repos that don't yet have an .nvmrc.  I kept forgetting to switch back when I left `frontend-platform`.

**Comment by binodpant** [comment]
Closing this task per discussion with team last week.

The idea is that we have done the preliminary investigation into how we will proceed.

A new set of issues will be created under the Milestone 'node 16 upgrade' to execute specific tasks. But this task can be considered closed now.

Here is a quick summary of how we will proceed:

Document laying out the process that will be followed:

https://openedx.atlassian.net/wiki/spaces/AC/pages/3318054984/Node+16+Upgrade

Feedback on process/improvements, will be taken/discussed in the document and/or in the weekly meetup for the FWG.

See the milestone for further updates on this project: https://github.com/openedx/frontend-wg/milestone/9
