### ISSUE TITLE
Add documentation example of showing a step in an error state

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/frontend-wg#51]
Paragon ticket: https://openedx.atlassian.net/browse/PAR-638

### Description

On the [existing documentation](https://paragon-edx.netlify.app/components/stepper/) for `Stepper`, there is no indication that a step may be configured to be in an error state, unless you realize that by looking at the props API and/or the Figma spec.

![image](https://user-images.githubusercontent.com/2828721/149195908-ee1edc92-cc5e-46ee-8e13-6fe5694a28bd.png)

**AC**
* As an engineer, I should be able to see on the documentation site that a step can be configured in an error state with an optional description for the step.

**Comment by bseverino** [comment]
Wanted to note before I forget: while working on this, I noticed a bug. If a step is updated, it seems to get deleted and readded to the end of the list. So if the first step here enters an error state:

![Screen Shot 2022-01-13 at 10 01 02 AM](https://user-images.githubusercontent.com/10442143/149978501-10047db6-9883-4053-819b-04225999ae43.png)

The offending step gets sent to the end of the list instead of holding its place:

![Screen Shot 2022-01-13 at 10 01 14 AM](https://user-images.githubusercontent.com/10442143/149978595-cc99bb48-65cc-417d-888c-49060a4bf70f.png)

Looking through our codebase, the only place we're using this is in the [course authoring MFE](https://github.com/openedx/frontend-app-course-authoring/blob/c7fd33f99e74578709ca8226651c66204dcb72e1/src/pages-and-resources/discussions/DiscussionsSettings.jsx), but it's only possible to enter an error state on the last step of the component, so the order wouldn't matter.

I believe this is the line that's causing it but I haven't had a chance to test out a fix yet: https://github.com/openedx/paragon/blob/master/src/Stepper/StepperStep.jsx#L23

**Comment by bseverino** [comment]
^ snippet for the example above:

```jsx
() => {
  const steps = ['checkbox', 'success'];
  const [currentStep, setCurrentStep] = useState(steps[0]);
  const [isChecked, check, uncheck, toggleChecked] = useToggle(false);
  const [hasError, setError, removeError] = useToggle(false);

  const evaluateCheckbox = () => {
    if (isChecked) {
      removeError();
      setCurrentStep('success');
    } else {
      setError();
    }
  };

  const resetCheckbox = () => {
    uncheck();
    removeError();
  };

  return (
    <Stepper activeKey={currentStep}>
      <Stepper.Header />

      <Container size="sm" className="py-5">
        <Stepper.Step
          eventKey="checkbox"
          title="Check the Box"
          description={hasError ? 'Please check the box to continue.' : ''}
          hasError={hasError}
        >
          <h2>Check the box</h2>
          <Form.Checkbox checked={isChecked} onChange={toggleChecked}>
            Check me!
          </Form.Checkbox>
        </Stepper.Step>

        <Stepper.Step eventKey="success" title="Success!">
          <h2>Success!</h2>
          <p>You may now complete this demo.</p>
        </Stepper.Step>
      </Container>

      <div className="py-3">
        <Stepper.ActionRow eventKey="checkbox">
          <Button variant="outline-primary" onClick={resetCheckbox}>
            Cancel
          </Button>
          <Stepper.ActionRow.Spacer />
          <Button onClick={() => evaluateCheckbox()}>Next</Button>
        </Stepper.ActionRow>

        <Stepper.ActionRow eventKey="success">
          <Button variant="outline-primary" onClick={() => setCurrentStep('checkbox')}>
            Previous
          </Button>
          <Stepper.ActionRow.Spacer />
          <Button onClick={() => alert('Completed')}>Complete</Button>
        </Stepper.ActionRow>
      </div>
    </Stepper>
  )
}
```
