### ISSUE TITLE
Frontend-build: investigate/solve issue between @svgr/webpack and webpack-dev-server 

### ISSUE THREAD

**Issue by dianekaplan** [openedx/frontend-wg#85]
**Summary**:  the combination of two packages make an issue where some MFEs won't build after being updated to use frontend-build 9.1.2; 'npm run build' fails after necessary files aren't written into the dist folder, making a fatal error when pushing to New Relic because the bundle doesn't exist. ( "@svgr/webpack": "6.2.1", "webpack-dev-server": "4.7.3",)

**Clues**: (from Michael Terry and Adam Stankiewicz)
- both of these packages are present in the new frontend-build version 9.1.2, but also the issue can be reproduced on version 9.1.1 after manually updating the dev-server to have both of those package versions (removing either one removes the problem)
- we've seen the issue updating payment MFE and learning MFE to frontend-build 9.1.2, BUT frontend-app-publisher is on frontend-build 9.1.2 and does NOT break. When trying on frontend-app-portal, Adam S hit the issue during the github CI check
- commenting out bundle analyzer plugin from the prod webpack config removes the “no file found” messages in the stack trace, BUT it still fails with the same issues as in the screenshot above.
- one possible suspect is a timing issue: it's like webpack-bundle-analyzer is incorrectly trying to parse dist before the files are actually put there.

**Comment by arbrandes** [comment]
Question came up during the last FWG meeting: the Node 16 upgrade was NOT the cause, it seems (it was tagged before 9.1.2).

**Comment by inventhouse** [comment]
What is the current status of this?  What can I do to help? (Note: I really don't know very much about `npm` nor `webpack`)

**Comment by arbrandes** [comment]
@inventhouse, the status is still as stated in the description.  We're looking for somebody to try and discover what exactly causes the issue, and then hopefully submit a patch to fix it.  If you do end up picking this up, you may find the discussion [on the last FWG meeting](https://drive.google.com/file/d/1iB5tV7rLYsuT2lltyI4XQ0j_rv5j_a6K/view?usp=sharing) about this useful.  (It starts at the 24'25'' mark, roughly.)

**Comment by ghassanmas** [comment]
I was looking into this, but couldn't reprodue it as (a **fatal error**) on (learning, account, and publisher MFEs)  what I got is (_warnings related @edx/paragon or/and react-responsive_) which I don't think that what this issue is concerned about, right?. 
My env while testing was: 
```
node -v: v12.21.0
npm -v: 6.14.11
```
Worth noting that webpack-dev-server support node >= 12.13, so may be check if that contraint is met on the env where it fails.
 
[ref](https://webpack.js.org/configuration/dev-server/): 
> Warning
webpack-dev-server v4.0.0+ requires node >= v12.13.0, webpack >= v4.37.0 (but we recommend using webpack >= v5.0.0), and webpack-cli >= v4.7.0.

**Comment by adamstankiewicz** [comment]
Also, it turns out the reproduction I thought I had seen in frontend-app-admin-portal when using frontend-build@9.1.2 was not related to frontend-build after all, but an issue within the consuming MFE.

So, frontend-app-admin-portal is also safely running frontend-build@9.1.2 in production as of this writing.

**Comment by inventhouse** [comment]
This is still blocking frontend-app-payment.

**Comment by arbrandes** [comment]
> This is still blocking frontend-app-payment.

@inventhouse, did https://github.com/openedx/frontend-app-payment/pull/579 fix the build?

**Comment by inventhouse** [comment]
With much help from @davidjoy we've found that frontend-app-payment's NewRelic setup was archaic, we're modernizing that and continuing to investigate.

**Comment by mikix** [comment]
Yes, looks like the header dependency updates also fixed the issue for `frontend-app-learning`? Presumably that's why we only saw the issue in gocd, not in github CI.

Yay! I'd say this issue could be closed then.
